import Head from 'next/head'
import Button from '@/Components/Button'
import Carousel from '../Components/Carousel1'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     {/* <Button buttonColor='yellow' buttonText='this is button' textColor='white' onHoverColor='white' variant=''/>
      this is home page */}
      <Carousel />
    </>
  )
}
