import Head from "next/head";
import React from "react";

import RoomTypes from "@RoomTypes/RoomTypes";
import Container from "@Container/Container";
import discoverImage from "@public/hero-images/discover.jpg";

export default function ChooseRoom() {
  return (
    <>
      <Head>
        <title>Choose Room | Hyge Paradise</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <RoomTypes />
    </>
  );
}
