import Head from "next/head";
import { useEffect, useState } from "react";

import Heading from "@Heading/Heading";
import Input from "@Form/Input";
import TextArea from "@Form/TextArea";
import Button from "@Button/Button";

export default function Contact() {
  const [isExpanded, setIsExpanded] = useState(false);

  useEffect(() => {
    if (window.innerWidth >= 768) {
      setIsExpanded(true);
    } else {
      setIsExpanded(false);
    }
  });

  return (
    <>
      <Head>
        <title>Contact | Hyge Paradise</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="lg:max-w-[1024px] md:mb-36">
        <Heading>Contact Us</Heading>
        <p className="uppercase font-bold text-white mt-8 mb-4 md:mb-8 md:font-normal md:normal-case">
          {isExpanded
            ? "We are here for you 24/7. Our Customer Success Team is called that way for a reason."
            : "Your Detail"}
        </p>
        <form className=" flex flex-col md:flex-row md:items-stretch gap-4 mb-4 items-center w-full">
          <div className="flex flex-col gap-4 md:justify-between w-full">
            <Input label="Your Name" />
            <Input label="Your Email" type="email" />
            <Input label="Your Phone" />
          </div>
          <TextArea label="Your Message" row={5} />
        </form>
        <Button className="flex justify-center" buttonClassName="md:w-36 px-8">
          Submit
        </Button>
      </div>
    </>
  );
}
