import { useMemo, useState, useEffect } from "react";
import Head from "next/head";

import Caraousel from "@Home/Caraousel";
import Facilities from "@Home/Facilities";
import Social from "@Social/Social";

import discoverImage from "@public/hero-images/discover.jpg";
import divineImage from "@public/hero-images/divine.png";
import paradiseImage from "@public/hero-images/paradise.jpg";

import type { CaraouselData } from "@Home/Caraousel/Caraousel";

export default function Home() {
	const caraouselData = useMemo<CaraouselData[]>(
		() => [
			{
				title: "Discover",
				image: discoverImage.src,
			},
			{
				title: "Divine",
				image: divineImage.src,
			},
			{
				title: "Paradise",
				image: paradiseImage.src,
			},
		],
		[]
	);

	const [isExpanded, setIsExpanded] = useState(false);

	useEffect(() => {
		if (window.innerWidth >= 1024) {
			setIsExpanded(true);
		} else {
			setIsExpanded(false);
		}
	});

	return (
		<>
			<Head>
				<title>Hyge Paradise</title>
				<meta name="description" content="Generated by create next app" />
			</Head>
			<main className="w-screen h-screen bg-black relative overflow-hidden">
				<Caraousel caraouselData={caraouselData} />
				<Facilities />
				{isExpanded && <Social variant="secondary" />}
			</main>
		</>
	);
}
